### ISSUE TITLE
Google Photo

### ISSUE THREAD

**Issue by elemwm** [nanostudio-org/nanogallery2#12]
Hi,
Is Google Photo still supported?
If I create new albums from Google Photo, the gallery doesn't display them.

Thanks

**Comment by Kris-B** [comment]
Hi, Google Photos is still supported but Google changed it's API behaviour yesterday and, at this time, it's no more possible de get access to newly created albums.

Unfortunately, there's nothing that can be changed in nanoGALLERY/nanogallery2 to solve this issue.

A lot of people are impcated and are trying to find a solution...
I'll post new informations as soon as I have some.

**Albums created before the 9th february 2017 are not concerned by this issue.**


FYI:
https://groups.google.com/forum/#!msg/google-picasa-data-api/avU2e9Ty2uA/70ZhB-uTDwAJ
https://developers.google.com/picasa-web/docs/3.0/releasenotes

**Comment by Kris-B** [comment]
Hey, I could find a new way to access Google Photos.
It's implemented in v0.9.3.

You'll also need a server side component: https://github.com/nanostudio-org/nanogp
That's because Google Photos account owner needs to grant authorization to the application which wants to access the data. Only server-side applications can be granted permanently.

The builder has been adapted: http://nanogallery2.nanostudio.org/builder.html
