### ISSUE TITLE
Container height

### ISSUE THREAD

**Issue by humbertorodrigues** [nanostudio-org/nanogallery2#151]
Hello guys!

This plugin is just awesome.
But, I have one doubt: if I have 300 images to load as a justified gallery, the plugin will make the container height as tall as necessary to hold all images even if I haven't scrolled down the page. Any idea of what can I do to do not have a containar with 10k pixels when I have only 10 images loaded yet?

**Comment by Kris-B** [comment]
you may set the value `moreButton` to the option `galleryDisplayMode`
please check https://nanogallery2.nanostudio.org/documentation.html#ngy2_gallery

**Comment by bhartvigsen** [comment]
> you may set the value `moreButton` to the option `galleryDisplayMode`
> please check https://nanogallery2.nanostudio.org/documentation.html#ngy2_gallery

This makes no sense though. What is the point of having lazy-loading if it is incapable of rendering?

**Comment by Kris-B** [comment]
sorry I don't understand what you mean...

the container is as height as the gallery, so one can for example go to the end of the gallery without having to load all the thumbnails step by step all the way to the bottom

**Comment by bhartvigsen** [comment]
Yes but the issue is that it's impossible to use lazy loading inside a modal or other container because the content either scrolls out of its container OR with proper CSS fails to lazy load because the content never hits viewport bottom.

For those struggling with this issue, the workaround that I found was to use the 'load more' mode and then fire a 'click' at the button when the user scrolls to the bottom of your container.

**Comment by joelz** [comment]
@bhartvigsen my two cents to the issue you described about gallery in a modal : [113#issuecomment-453372321](https://github.com/nanostudio-org/nanogallery2/issues/113#issuecomment-453372321)
