### ISSUE TITLE
Will nanogallery2 continue to work after the Picasa Web Albums Data API is deprecated in January 2019?

### ISSUE THREAD

**Issue by ryanderson** [nanostudio-org/nanogallery2#153]
I am looking to purchase an OEM license for unlimited websites, to update all my client websites to NanoGallery2 fromthe "Picasa Webalbum Integrator" jQuery Plugin (https://code.google.com/archive/p/pwi/) that is no longer working due to it using the soon to be deprecated Picasa Web Albums Data API.

Will NanoGallery2 continue to work after the Picasa Web Albums Data API is deprecated in January 2019, as it looks to use some calls to that API in some of the code?

The deprecation notice is here: https://developers.google.com/picasa-web/docs/3.0/deprecation

**Comment by Kris-B** [comment]
In order to continue to use Google Photos after the 15 march 2019, you'll have to use:
- nanogallery2 v2.4.0
Beta available here: https://github.com/nanostudio-org/nanogallery2/tree/dev
- nanogp2
Beta available here: https://github.com/nanostudio-org/nanogp2
Documentation is not fully finished, but the add-on is working.

Please note:
- album'IDs have changed
- there's an option for generating a list of albums (including their IDs) for one specific user

**Comment by Kris-B** [comment]
please upgrade to
- nanogp2 v2.0.1 - https://github.com/nanostudio-org/nanogp2
- nanogallery2 v2.4.0 - https://github.com/nanostudio-org/nanogallery2/releases/tag/v2.4.0

**Comment by Kris-B** [comment]
I'm closing this issue as it's not directly related to nanogallery2.
You may open a new issue on the nanogp repository: https://github.com/nanostudio-org/nanogp2
